name: "Build & Deploy"

on:  
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync files to S3
        run: |
            aws s3 rm s3://${{ secrets.S3_BUCKET_NAME }} --recursive --include "*"
            aws s3 sync ./ s3://${{ secrets.S3_BUCKET_NAME }} --exclude ".*" --delete

      - name: Invalidate CloudFront Cache
        run: |
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

